export const environment =  {
  USER: process.env.APOYO_ALIMENTARIO_CRUD_USER,
  PASS: process.env.APOYO_ALIMENTARIO_CRUD_PASS,
  HOST: process.env.APOYO_ALIMENTARIO_CRUD_HOST,
  PORT: process.env.APOYO_ALIMENTARIO_CRUD_PORT,
  DB: process.env.APOYO_ALIMENTARIO_CRUD_DB,
  HTTP_PORT: process.env.APOYO_ALIMENTARIO_CRUD_HTTP_PORT,
  AUTH_DB: process.env.APOYO_ALIMENTARIO_CRUD_AUTH_DB 
};